apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: category-service
  name: category-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: category-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: category-service
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              value: your_jwt_secret
            - name: MONGO_URL
              value: mongodb://mongodb:27017/categories
            - name: PORT
              value: "7004"
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672
          image: category-service
          name: category-service
      restartPolicy: Always
