apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: order-service
    spec:
      containers:
        - env:
            - name: CART_SERVICE_URL
              value: http://cart-service:7003
            - name: JWT_SECRET
              value: your_jwt_secret
            - name: MONGO_URL
              value: mongodb://mongodb:27017/orders
            - name: PORT
              value: "7005"
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:7002
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672
            - name: USER_SERVICE_URL
              value: http://user-service:7001
          image: order-service
          name: order-service
      restartPolicy: Always
